#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Module-Template-Setup
version:      0.02
version_from: lib/Module/Template/Setup.pm
installdirs:  site
requires:
    CGI::FastTemplate:             0
    Test::Pod::Coverage:           0.08
    Test::More:                    0
    Carp:                          0
    Env:                           0
    Test::Pod:                     0.95
    File::Find:                    0
    Cwd:                           0
    File::Spec:                    0
    Config::Simple:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
